name: E2E on Chrome
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: Cypress
    steps:
      - uses: actions/checkout@v1

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"

      - run: pnpm install

      - run: pnpm run build

      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
