name: E2E on Chrome
on: [push, pull_request]
jobs:
  cypress-run:
    name: Cypress

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: pnpm install

      - run: pnpm build

      - uses: cypress-io/github-action@v5
        with:
          browser: chrome

      - uses: JS-DevTools/npm-publish@v3
        id: publish
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
          tag: latest
          access: public
          dry-run: false
          check-version: true
          greater-version-only: true

      - name: Tag
        if: github.ref_name == 'main' && steps.publish.outputs.type != 'none'
        uses: anothrNick/github-tag-action@v1
        env:
          CUSTOM_TAG: ${{ steps.publish.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: github.ref_name == 'main' && steps.publish.outputs.type != 'none'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.publish.outputs.version }}
          body:
            'Changelog: https://github.com/iendeavor/object-visualizer/blob/${{ steps.publish.outputs.version
            }}/CHANGELOG.md'
